# MIT 6.036 Spring 2019: Homework 6

This homework does not include provided Python code. Instead, we encourage you to write your own code to help you answer some of these problems, and/or test and debug the code components we do ask for. All of the problems should be simple enough that hand calculation should be possible, but it may be convenient to write some short programs to explore the neural networks, particularly for problem 2.


In [ ]:
import numpy as np

def SM(z):
    # Compute the softmax of vector z
    exp_z = np.exp(z)
    return exp_z / np.sum(exp_z)

 **Problem 2A**

In [ ]:
z = np.array([[-1, 0, 1]]).T
# Apply the softmax function
a = SM(z)

# Print the resulting probability distribution
print(a)


[[0.09003057]
 [0.24472847]
 [0.66524096]]


Problem 2B

In [ ]:
import numpy as np

def nll(a, y):
    # Compute NLL directly without clipping
    return -np.sum(y * np.log(a) + (1 - y) * np.log(1 - a))

# Given arrays
a = np.array([[0.3], [0.5], [0.2]])  # (3, 1)
y = np.array([[0], [0], [1]])        # (3, 1)

# Compute and print NLL
nll_value = nll(a, y)
print(nll_value)

# Print result with natural log value
print(f"NLL: {nll_value}")
print(f"-log(0.2) = {np.log(1 / 0.2)}")


2.6592600369327783
NLL: 2.6592600369327783
-log(0.2) = 1.6094379124341003


**Problem 2.C-F**

In [ ]:
#w = np.array([[1, -1, -2], [-1, 2, 1]])
#x = np.array([[1], [1]])
#y = np.array([[0, 1, 0]]).T
# your code here
import numpy as np

def softmax(z):
    exp_z = np.exp(z)
    return exp_z / np.sum(exp_z)

# Weight matrix
w = np.array([[1, -1, -2], [-1, 2, 1]])

# Input vector x
x = np.array([[1], [1]])

# Target output y
y = np.array([[0, 1, 0]]).T

# Compute pre-activation values z^L
z = np.dot(w.T, x)

# Compute softmax probabilities a^L
a = softmax(z)

# Compute the gradient of the weights with respect to the NLL
gradient = np.dot(x, (a - y).T)

# Print the gradient
print("Gradient of the weights with respect to NLL:")
print(gradient)




Gradient of the weights with respect to NLL:
[[ 0.24472847 -0.33475904  0.09003057]
 [ 0.24472847 -0.33475904  0.09003057]]


***Predicting probability of class for x  ***

In [ ]:
import numpy as np

def softmax(z):
    exp_z = np.exp(z)
    return exp_z / np.sum(exp_z)

# Initial weight matrix
w = np.array([[1, -1, -2], [-1, 2, 1]])  # Shape (2, 3)

# Input vector x
x = np.array([[1], [1]])  # Shape (2, 1)

# Target output y
y = np.array([[0, 1, 0]]).T  # Shape (3, 1)

# Compute pre-activation values z^L before gradient update
z = np.dot(w.T, x)  # Shape (3, 1)

# Compute softmax probabilities a^L before gradient update
a = softmax(z)

# Print probabilities before the gradient update
print("Probabilities before gradient update:")
print(a)

# Determine the predicted class before the gradient update
predicted_class_before = np.argmax(a) + 1
print(f"Predicted class before gradient update: {predicted_class_before}")

# Compute the gradient of the weights with respect to NLL
gradient = np.dot(x, (a - y).T)  # Shape (2, 3)

# Update weights (assume a small learning rate, e.g., lr = 0.1)
learning_rate = 0.1
w_new = w - learning_rate * gradient  # No transpose, gradient is (2, 3)

# Compute pre-activation values z^L after gradient update
z_new = np.dot(w_new.T, x)  # Shape (3, 1)

# Compute softmax probabilities a^L after gradient update
a_new = softmax(z_new)

# Print probabilities after the gradient update
print("Probabilities after gradient update:")
print(a_new)

# Determine the predicted class after the gradient update
predicted_class_after = np.argmax(a_new) + 1
print(f"Predicted class after gradient update: {predicted_class_after}")


Probabilities before gradient update:
[[0.24472847]
 [0.66524096]
 [0.09003057]]
Predicted class before gradient update: 2
Probabilities after gradient update:
[[0.22564471]
 [0.6887368 ]
 [0.08561849]]
Predicted class after gradient update: 2


Using step size 0.5

In [ ]:
#import numpy as np

#def softmax(z):
#    exp_z = np.exp(z)
#    return exp_z / np.sum(exp_z)

# Initial weight matrix
w = np.array([[1, -1, -2], [-1, 2, 1]])  # Shape (2, 3)

# Input vector x
x = np.array([[1], [1]])  # Shape (2, 1)

# Target output y
y = np.array([[0, 1, 0]]).T  # Shape (3, 1)

# Compute pre-activation values z^L before gradient update
z = np.dot(w.T, x)  # Shape (3, 1)

# Compute softmax probabilities a^L before gradient update
a = softmax(z)

# Print probabilities before the gradient update
print("Probabilities before gradient update:")
print(a)

# Determine the predicted class before the gradient update
predicted_class_before = np.argmax(a) + 1
print(f"Predicted class before gradient update: {predicted_class_before}")

# Compute the gradient of the weights with respect to NLL
gradient = np.dot(x, (a - y).T)  # Shape (2, 3)

# Update weights with step size 0.5 (learning rate = 0.5)
learning_rate = 0.5
w_new = w - learning_rate * gradient  # Shape (2, 3)

# Print the updated weight matrix
print("Updated weight matrix WL after one gradient update step with step size 0.5:")
print(w_new)

# Compute pre-activation values z^L after gradient update
z_new = np.dot(w_new.T, x)  # Shape (3, 1)

# Compute softmax probabilities a^L after gradient update
a_new = softmax(z_new)

# Print probabilities after the gradient update
print("Probabilities after gradient update:")
print(a_new)

# Determine the predicted class after the gradient update
predicted_class_after = np.argmax(a_new) + 1
print(f"Predicted class after gradient update: {predicted_class_after}")


Probabilities before gradient update:
[[0.24472847]
 [0.66524096]
 [0.09003057]]
Predicted class before gradient update: 2
Updated weight matrix WL after one gradient update step with step size 0.5:
[[ 0.87763576 -0.83262048 -2.04501529]
 [-1.12236424  2.16737952  0.95498471]]
Probabilities after gradient update:
[[0.15918761]
 [0.77245284]
 [0.06835955]]
Predicted class after gradient update: 2


***Find the predicted probability that x is in class 1 using the updated weight matrix***

In [ ]:
import numpy as np

def softmax(z):
    exp_z = np.exp(z)
    return exp_z / np.sum(exp_z)

# Updated weight matrix WL after the gradient update
new_w = np.array([[ 0.87763576, -0.83262048, -2.04501529],
                  [-1.12236424,  2.16737952,  0.95498471]])  # Shape (2, 3)

# Input vector x
x = np.array([[1], [1]])  # Shape (2, 1)

# Compute the pre-activation values z^L using the updated weight matrix
new_z = np.dot(new_w.T, x)  # Shape (3, 1)

# Compute the softmax probabilities a^L
new_a = softmax(new_z)

# Print the predicted probabilities
print("Predicted probabilities (in order of classes 2, 1, boundary):", new_a)

# Mapping probabilities to classes based on the guide's hint
prob_class_2 = new_a[0, 0]  # First element for class 2
prob_class_1 = new_a[1, 0]  # Second element for class 1
prob_boundary = new_a[2, 0]  # Third element for the boundary class

print(f"Predicted probability for class 1: {prob_class_1}")
print(f"Predicted probability for class 2: {prob_class_2}")
print(f"Predicted probability for boundary: {prob_boundary}")


Predicted probabilities (in order of classes 2, 1, boundary): [[0.15918761]
 [0.77245284]
 [0.06835955]]
Predicted probability for class 1: 0.7724528373387168
Predicted probability for class 2: 0.15918760859452763
Predicted probability for boundary: 0.06835955406675555


**Problem 3**

In [ ]:
# layer 1 weights
w_1 = np.array([[1, 0, -1, 0], [0, 1, 0, -1]])
w_1_bias = np.array([[-1, -1, -1, -1]]).T
# layer 2 weights
w_2 = np.array([[1, -1], [1, -1], [1, -1], [1, -1]])
w_2_bias = np.array([[0, 2]]).T

# your code here

In [ ]:
import numpy as np

T  = np.matrix([[0.0 , 0.1 , 0.9 , 0.0],
[0.9 , 0.1 , 0.0 , 0.0],
[0.0 , 0.0 , 0.1 , 0.9],
[0.9 , 0.0 , 0.0 , 0.1]])
g = 0.9
r = np.matrix([0, 1., 0., 2.]).reshape(4, 1)

print(np.linalg.solve(np.eye(4) - g * T, r))

[[6.05288295]
 [6.48663207]
 [6.7519581 ]
 [7.58553317]]
